#数据库加密配置
dbcrypt:
  secretkey: 123456789012345678901234
  enable: true
  primaryKeyName: id

#数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/crypt_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatisplus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.kamjin1996.mybatisdemo.entity

